//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelOtomasyonu.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbOtelEntities : DbContext
    {
        public DbOtelEntities()
            : base("name=DbOtelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Birim> Birim { get; set; }
        public virtual DbSet<Departman> Departman { get; set; }
        public virtual DbSet<Durum> Durum { get; set; }
        public virtual DbSet<Gorev> Gorev { get; set; }
        public virtual DbSet<Kasa> Kasa { get; set; }
        public virtual DbSet<Kur> Kur { get; set; }
        public virtual DbSet<Misafir> Misafir { get; set; }
        public virtual DbSet<Oda> Oda { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Telefon> Telefon { get; set; }
        public virtual DbSet<Ulke> Ulke { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<UrunGrup> UrunGrup { get; set; }
    }
}
