//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PersonelId { get; set; }
        public string AdSoyad { get; set; }
        public string Tc { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> IseGirisTarihi { get; set; }
        public Nullable<System.DateTime> IstenCikisTarihi { get; set; }
        public Nullable<int> Departman { get; set; }
        public Nullable<int> Gorev { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Durum { get; set; }
        public string KimlikOn { get; set; }
        public string KimlikArka { get; set; }
        public string Yetki { get; set; }
        public string Sifre { get; set; }
    
        public virtual Departman Departman1 { get; set; }
        public virtual Durum Durum1 { get; set; }
        public virtual Gorev Gorev1 { get; set; }
    }
}
