//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Misafir
    {
        public int MisafirId { get; set; }
        public string AdSoyad { get; set; }
        public string Tc { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Ulke { get; set; }
        public string Aciklama { get; set; }
        public string KimlikFoto1 { get; set; }
        public string KimlikFoto2 { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<int> Sehir { get; set; }
        public Nullable<int> ilce { get; set; }
    
        public virtual Tbl_Durum Tbl_Durum { get; set; }
        public virtual Tbl_Ulke Tbl_Ulke { get; set; }
    }
}
