//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Misafir
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Misafir()
        {
            this.Tbl_Rezervasyon = new HashSet<Tbl_Rezervasyon>();
        }
    
        public int MisafirId { get; set; }
        public string AdSoyad { get; set; }
        public string Tc { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Ulke { get; set; }
        public string Aciklama { get; set; }
        public string KimlikFoto1 { get; set; }
        public string KimlikFoto2 { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<int> Ilce { get; set; }
        public Nullable<int> Sehir { get; set; }
    
        public virtual Tbl_Durum Tbl_Durum { get; set; }
        public virtual Tbl_Ulke Tbl_Ulke { get; set; }
        public virtual ilceler ilceler { get; set; }
        public virtual iller iller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Rezervasyon> Tbl_Rezervasyon { get; set; }
    }
}
